import "./globals.css";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@material-tailwind/react";
import Footer from "@/components/Footer";
import SecondHeader from "@/components/SecondHeader";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <SecondHeader />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
