"use client";
import "./globals.css";
import { Inter } from "next/font/google";

import Footer from "@/components/Footer";
import SecondHeader from "@/components/SecondHeader";
import Main from "@/components/Main";
const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Main>
          <SecondHeader />
          {children}
          <Footer />
        </Main>
      </body>
    </html>
  );
}
